### ISSUE TITLE
Rotating error

### ISSUE THREAD

**Issue by Deluxe4arms** [jacksight/xina520_official_jailbreak#16]
When I boot into the jailbroken side, I am unable to rotate my iPad Pro 2018.

**Comment by cyndicati0n** [comment]
Additional info:
- Initial jailbreak with safe mode (No restart for the first time)
- Reboot or Respring
- Jailbreak without safe mode
- Respring, rotation restored
Side-effects:
- Bypass applications (a-bypass, hestia) fail to start. Causing the enabled applications for bypass to no longer load. Till disabled.

Will continue to test, and validate additional steps to see if root cause can be identified.

**Comment by Deluxe4arms** [comment]
Thank you
