### ISSUE TITLE
Unable to change ssh password using “passwd” command

### ISSUE THREAD

**Issue by mio-19** [jacksight/xina520_official_jailbreak#53]

**Comment by firashacker** [comment]
fix this pls 🥲💔 this makes the jailbreak so risky

**Comment by 22localport** [comment]
Well, it seems this is a problem caused by the rootful bootstrap in xinaa15. Xina uses a patched ios13 procursus bootstrap, and it handles several things incorrectly including passwd not functioning. This perhaps can be solved by changing to a bootstrap developed properly for rootless jailbreaks, although xina's unlikely to get further builds.

**Comment by mio-19** [comment]
> fix this pls 🥲💔 this makes the jailbreak so risky

A workaround is to disable password login and use public keys

**Comment by jacksight** [comment]
> Well, it seems this is a problem caused by the rootful bootstrap in xinaa15. Xina uses a patched ios13 procursus bootstrap, and it handles several things incorrectly including passwd not functioning. This perhaps can be solved by changing to a bootstrap developed properly for rootless jailbreaks, although xina's unlikely to get further builds.

Thanks for the explanation!!!

**Comment by jacksight** [comment]
> > fix this pls 🥲💔 this makes the jailbreak so risky
> 
> 
> 
> A workaround is to disable password login and use public keys

I'm not sure if ssh key method is feasible or not, I'll try it out
